name = "MLSuiteBase"
uuid = "d01462b0-16b5-11ea-1c8e-eb7ed7586854"
authors = ["Yao Lu <luyaocns@gmail.com>"]
version = "0.2.3"

[deps]
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
ScikitLearnBase = "6e75b9c4-186b-50bd-896f-2d2496a4843e"

[compat]
Glob = "1"
JSON = "0.21"
ScikitLearnBase = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
